language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
cache: pip

install: pip install -r requirements.txt

script: py.test --cov=scraper.py

after_success:
  - bash <(curl -s https://cov.lanlytics.com/bash) -t "zvYVxfDUQ2Swtbv11JFS" -r arnold/data-feed
