language: python
dist: trusty
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
cache: pip

install: 
  - pip install -e .[dev]
  - pip install beautifulsoup4 lxml

script: py.test --cov data_feed

after_success:
  - bash <(curl -s https://cov.lanlytics.com/bash) -t "zvYVxfDUQ2Swtbv11JFS" -r nisac/data-feed
