language: python
dist: trusty
python:
  - "3.6"
  - "3.5"
  - "3.4"
cache: pip

install: 
  - pip install -r requirements.txt
  - pip install beautifulsoup4 lxml

script: py.test --cov=scraper.py --cov=subscriber.py --cov=noaa_wind_scraper.py

after_success:
  - bash <(curl -s https://cov.lanlytics.com/bash) -t "zvYVxfDUQ2Swtbv11JFS" -r nisac/data-feed
